# Generated by Django 5.1.2 on 2024-11-09 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=100)),
                ('race_date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RaceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib', models.CharField(default='', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.race')),
            ],
        ),
        migrations.CreateModel(
            name='RaceTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('checkpoint_number', models.PositiveIntegerField()),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_timings', to='api.racedata')),
            ],
        ),
        migrations.AddConstraint(
            model_name='racedata',
            constraint=models.UniqueConstraint(fields=('race', 'bib'), name='unique_race_bib'),
        ),
    ]
