# Generated by Django 5.1.2 on 2024-12-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_racetiming_timestamp'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='racetiming',
            constraint=models.UniqueConstraint(fields=('runner', 'checkpoint_number'), name='unique_race_timing'),
        ),
    ]
