# Generated by Django 5.1.2 on 2024-12-01 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_racetiming_unique_race_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racetiming',
            name='runner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race_timings', to='api.racedata'),
        ),
    ]
